package dw.com.file;
// Generated 19/02/2015 04:27:53 PM by Hibernate Tools 4.0.0



/**
 * PaginasId generated by hbm2java
 */
public class PaginasId  implements java.io.Serializable {


     private String urlPagina;
     private String descripcionPagina;

    public PaginasId() {
    }

	
    public PaginasId(String urlPagina) {
        this.urlPagina = urlPagina;
    }
    public PaginasId(String urlPagina, String descripcionPagina) {
       this.urlPagina = urlPagina;
       this.descripcionPagina = descripcionPagina;
    }
   
    public String getUrlPagina() {
        return this.urlPagina;
    }
    
    public void setUrlPagina(String urlPagina) {
        this.urlPagina = urlPagina;
    }
    public String getDescripcionPagina() {
        return this.descripcionPagina;
    }
    
    public void setDescripcionPagina(String descripcionPagina) {
        this.descripcionPagina = descripcionPagina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaginasId) ) return false;
		 PaginasId castOther = ( PaginasId ) other; 
         
		 return ( (this.getUrlPagina()==castOther.getUrlPagina()) || ( this.getUrlPagina()!=null && castOther.getUrlPagina()!=null && this.getUrlPagina().equals(castOther.getUrlPagina()) ) )
 && ( (this.getDescripcionPagina()==castOther.getDescripcionPagina()) || ( this.getDescripcionPagina()!=null && castOther.getDescripcionPagina()!=null && this.getDescripcionPagina().equals(castOther.getDescripcionPagina()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUrlPagina() == null ? 0 : this.getUrlPagina().hashCode() );
         result = 37 * result + ( getDescripcionPagina() == null ? 0 : this.getDescripcionPagina().hashCode() );
         return result;
   }   


}


