package dw.com.file;
// Generated 19/02/2015 04:27:53 PM by Hibernate Tools 4.0.0



/**
 * Paginas generated by hbm2java
 */
public class Paginas  implements java.io.Serializable {


     private PaginasId id;

    public Paginas() {
    }

    public Paginas(PaginasId id) {
       this.id = id;
    }
   
    public PaginasId getId() {
        return this.id;
    }
    
    public void setId(PaginasId id) {
        this.id = id;
    }




}


